//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachQuyen
    {
        public DanhSachQuyen()
        {
            this.PhanQuyens = new HashSet<PhanQuyen>();
        }
    
        public int IdQuyen { get; set; }
        public string TenQuyen { get; set; }
    
        public virtual ICollection<PhanQuyen> PhanQuyens { get; set; }
    }
}
