//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int IdUser { get; set; }
        public Nullable<int> IdQuyen { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<bool> IsEdit { get; set; }
    
        public virtual DanhSachQuyen DanhSachQuyen { get; set; }
    }
}
